apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provider
  namespace: kube-system
spec:
  project: default 
  source:
    repoURL: https://github.com/gilbertolaus/challenge-aquarela.git
    targetRevision: HEAD
    path: apps/local-path-provider/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true