apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://github.com/gilbertolaus/challenge-aquarela.git
    targetRevision: HEAD
    path: apps/bitwarden/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true