apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: bitwardenrs/server:latest
          ports:
            - containerPort: 80
          env:
            - name: BW_DOMAIN
              value: "http://localhost"  # Ajuste para seu domínio