apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        kubernetes default.svc.cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.18.0.1 host.k3d.internal
    172.18.0.5 k3d-devsecops-cluster-serverlb
    172.18.0.2 k3d-devsecops-cluster-server-0
    172.18.0.4 k3d-devsecops-cluster-agent-1
    172.18.0.3 k3d-devsecops-cluster-agent-0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    kubernetes default.svc.cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    kubernetes default in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    hosts /etc/coredns/NodeHosts {\n      ttl 60\n      reload 15s\n      fallthrough\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n    import /etc/coredns/custom/*.override\n}\nimport /etc/coredns/custom/*.server\n","NodeHosts":"172.18.0.1 host.k3d.internal\n172.18.0.5 k3d-devsecops-cluster-serverlb\n172.18.0.2 k3d-devsecops-cluster-server-0\n172.18.0.4 k3d-devsecops-cluster-agent-1\n172.18.0.3 k3d-devsecops-cluster-agent-0\n"},"kind":"ConfigMap","metadata":{"annotations":{"objectset.rio.cattle.io/applied":"H4sIAAAAAAAA/4yQQW/UMBCF/4o158Ssk90mWOKAekFCcOTUy8SeNCbemZXHDapW/e8oWkBIqMDtWc/z6b13BbykL1Q0CYOHzUEDESuCv8K9FJpTJvBg/ak31wc2xhgqRYre9EKY63LThTA+3+T6NFFhqqQm5CetVGwWaOCzRPogWhU8uKGzbrQH68wiWu3aR5u4UmHMD/zLPZm1j22kTSnIRdsfvFYJXhpYE0fwcC88p8dPeIEGzlTxZwNkloo1Cev+lOkrhapUbUliA9aaySZ5k3YGNK/68o2ptI/bCh7WXn9zNteYj4nju/cxCv8TwXje1wxSKLL+13e9YNhv9klbfdZK5714xonyX0stqAt4mAJ1Y9+9HUfnhmOPh368w+nkDnM33w00D8fueAinYYf+Ee/VAC/fAwAA///5C6FuOAIAAA","objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/owner-gvk":"k3s.cattle.io/v1, Kind=Addon","objectset.rio.cattle.io/owner-name":"coredns","objectset.rio.cattle.io/owner-namespace":"kube-system"},"creationTimestamp":"2025-02-13T22:15:03Z","labels":{"objectset.rio.cattle.io/hash":"bce283298811743a0386ab510f2f67ef74240c57"},"name":"coredns","namespace":"kube-system","resourceVersion":"10169","uid":"bd535f29-41a6-469b-a3ff-20deacfc1e67"}}
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQQW/UMBCF/4o158Ssk90mWOKAekFCcOTUy8SeNCbemZXHDapW/e8oWkBIqMDtWc/z6b13BbykL1Q0CYOHzUEDESuCv8K9FJpTJvBg/ak31wc2xhgqRYre9EKY63LThTA+3+T6NFFhqqQm5CetVGwWaOCzRPogWhU8uKGzbrQH68wiWu3aR5u4UmHMD/zLPZm1j22kTSnIRdsfvFYJXhpYE0fwcC88p8dPeIEGzlTxZwNkloo1Cev+lOkrhapUbUliA9aaySZ5k3YGNK/68o2ptI/bCh7WXn9zNteYj4nju/cxCv8TwXje1wxSKLL+13e9YNhv9klbfdZK5714xonyX0stqAt4mAJ1Y9+9HUfnhmOPh368w+nkDnM33w00D8fueAinYYf+Ee/VAC/fAwAA///5C6FuOAIAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2025-02-13T22:15:03Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "10744"
  uid: bd535f29-41a6-469b-a3ff-20deacfc1e67
